name: Multistep

on: push


jobs:
  build:
   runs-on: ubuntu-latest
  steps:
        - name: Echo the current time
          run: echo "The current server time is ${date}"
        - name: Echoing the current time again
          run: echo " The current time again is ${date}"  
